
version: "2.2"
services:

  jupyter:
    build:
      context: ./
      dockerfile: ./dockerfiles/pyspark.Dockerfile
    environment:
      PYSPARK_DRIVER_PYTHON: jupyter
      PYSPARK_DRIVER_PYTHON_OPTS: "notebook --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''"
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 0.0.0.0
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/usr/src/app/notebooks 
      - ./data:/usr/src/app/data
    command: //usr/spark-3.0.1/bin/pyspark

  master:
    build:
      context: ./
      dockerfile: ./dockerfiles/pyspark.Dockerfile
    command: /usr/spark-3.0.1/bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 0.0.0.0
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./config/spark/master:/conf:ro
      - ./notebooks:/usr/src/app/notebooks 
      - ./data:/usr/src/app/data

  worker:
    build:
      context: ./
      dockerfile: ./dockerfiles/pyspark.Dockerfile
    command: /usr/spark-3.0.1/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: 0.0.0.0
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./config/spark/worker:/conf:ro
      - ./notebooks:/usr/src/app/notebooks 
      - ./data:/usr/src/app/data